USE customer_shopping;

SELECT * FROM customer_shopping_data LIMIT 20;
-- 1) what is the total revenue generated by male vs female
--  customers?

SELECT gender ,SUM(purchase_amount) as revenue
from customer_shopping_data
group by gender;

-- 2) which customers used a discount but still spent more 
-- than the average purchase amount?

SELECT customer_id , purchase_amount
from customer_shopping_data
WHERE discount_applied = 'yes' and purchase_amount >= 
(select AVG(purchase_amount) from customer_shopping_data);

-- 3) which are the top 5 products with the highest average
--  review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4)compare the average purchase amounts between standard
--  and express shipping

SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
from customer_shopping_data    
WHERE shipping_type in ('Standard','Express')
group by shipping_type;

-- 5)Do subscribed customers spend more ? compare average
--  spend and total revenue between subscribers and non -
--  subscribers?

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer_shopping_data
group by subscription_status
order by total_revenue,avg_spend desc;

-- 6)which 5 products havethe highest percentage of purchases
--  with discount applied?

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 else 0 end)/ COUNT(*),2) as discount_rate 
FROM customer_shopping_data
group by item_purchased
order by discount_rate desc
limit 5;

-- 7)Segment customers into new ,returning and loyal based on
--  their total number of previous purchases and show count
--  of each segment?

with customer_type as (
select customer_id,previous_purchases,
CASE
WHEN previous_purchases=1 THEN 'NEW'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
from customer_shopping_data
)
SELECT customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- 8)what are the top 3  most purchased products within each
--  category?

with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) AS item_rank
from customer_shopping_data
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
WHERE item_rank <= 3

-- 9)are customers who are repeat buyers (more than 5 previous
--  purchases) also likely to subscribe)?

SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_data
where previous_purchases >5
group by subscription_status

-- 10) what is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) as total_revenue
from customer_shopping_data
group by age_group
order by  total_revenue desc;

